# .github/workflows/firebase-hosting-deploy.yml

name: Deploy Website to Firebase Hosting

on:
  push:
    branches:
      - master  # Ou a branch que você usa como principal
    paths:
      - 'firebase/hosting/**' # Executa a action apenas se houver mudanças na pasta do site

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Firebase
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRATICOS }}'

      - name: Setup Firebase CLI
        uses: FirebaseExtended/action-setup-firebase@v0
        with:
          version: latest

      - name: Deploy to Firebase Hosting
        working-directory: firebase
        run: firebase deploy --only hosting --project praticos
