# .github/workflows/firebase-hosting-deploy.yml

name: Deploy Website to Firebase Hosting

on:
  push:
    branches:
      - master  # Ou a branch que você usa como principal
    paths:
      - 'firebase/hosting/**' # Executa a action apenas se houver mudanças na pasta do site

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: firebase/hosting/package-lock.json

      - name: Install dependencies
        working-directory: firebase/hosting
        run: npm ci

      - name: Build site
        working-directory: firebase/hosting
        run: npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRATICOS }}'
          projectId: praticos
          channelId: live
          entryPoint: firebase
